### ISSUE TITLE
pwa not working in Firefox (works in Chrome)

### ISSUE THREAD

**Issue by n00b42** [c2FmZQ/c2FmZQ#48]
While trying to debug some issue, I tried to use your app instance on https://c2fmzq.org/pwa/
After `Enter a passphrase to encrypt your app data.`
the following error message pops up:
`TypeError: self.indexedDB.databases is not a function`
and then the site is reloaded.

**Comment by n00b42** [comment]
After updating my docker instance to the latest release, I get the same error.

**Comment by n00b42** [comment]
While I can not test v0.3.11 myslef, it worked with docker tag "n00b42", but stopped working from v0.4.0 to v0.4.9

**Comment by n00b42** [comment]
Does not work in Firefox (119.0), but does work in Chrome (119.0)
